dev:
  debug: false
  version: 0.1.1
  maintainer:
    name: Théo Vidal
    link: exybore@becauseofprog.fr
bot:
  name: XBOP-NX
  id: 796796572134015018
  illustration: https://cdn.discordapp.com/avatars/796796572134015018/4a600173aa979c7485ef2d3b193449a0.png?size=256
  website: https://github.com/BecauseOfProg/XBOP
  color: 6313215
cache:
  address: localhost
  port: 6379
